
#info(install/bash): Downloading tree-sitter-bash...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-bash/archive/a06c2e4415e9bc0346c6b86d401879ffb44058f7.tar.gz --output $HOME/.cache/nvim/tree-sitter-bash.tar.gz

#info(install/c): Downloading tree-sitter-c...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-c/archive/ae19b676b13bdcc13b7665397e6d9b14975473dd.tar.gz --output $HOME/.cache/nvim/tree-sitter-c.tar.gz

#info(install/diff): Downloading tree-sitter-diff...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-diff/archive/2520c3f934b3179bb540d23e0ef45f75304b5fed.tar.gz --output $HOME/.cache/nvim/tree-sitter-diff.tar.gz

#info(install/dockerfile): Downloading tree-sitter-dockerfile...
curl --silent --fail --show-error --retry 7 -L https://github.com/camdencheek/tree-sitter-dockerfile/archive/971acdd908568b4531b0ba28a445bf0bb720aba5.tar.gz --output $HOME/.cache/nvim/tree-sitter-dockerfile.tar.gz

#info(install/gitcommit): Downloading tree-sitter-gitcommit...
curl --silent --fail --show-error --retry 7 -L https://github.com/gbprod/tree-sitter-gitcommit/archive/33fe8548abcc6e374feaac5724b5a2364bf23090.tar.gz --output $HOME/.cache/nvim/tree-sitter-gitcommit.tar.gz

#info(install/gitignore): Downloading tree-sitter-gitignore... 
curl --silent --fail --show-error --retry 7 -L https://github.com/shunsambongi/tree-sitter-gitignore/archive/f4685bf11ac466dd278449bcfe5fd014e94aa504.tar.gz --output $HOME/.cache/nvim/tree-sitter-gitignore.tar.gz

#info(install/ini): Downloading tree-sitter-ini...
curl --silent --fail --show-error --retry 7 -L https://github.com/justinmk/tree-sitter-ini/archive/e4018b5176132b4f3c5d6e61cea383f42288d0f5.tar.gz --output $HOME/.cache/nvim/tree-sitter-ini.tar.gz

#info(install/jsdoc): Downloading tree-sitter-jsdoc...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-jsdoc/archive/658d18dcdddb75c760363faa4963427a7c6b52db.tar.gz --output $HOME/.cache/nvim/tree-sitter-jsdoc.tar.gz

#info(install/json): Downloading tree-sitter-json...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-json/archive/001c28d7a29832b06b0e831ec77845553c89b56d.tar.gz --output $HOME/.cache/nvim/tree-sitter-json.tar.gz

#info(install/kitty): Downloading tree-sitter-kitty...
curl --silent --fail --show-error --retry 7 -L https://github.com/OXY2DEV/tree-sitter-kitty/archive/fa6ab3fd32d890a0217495c96b35761e6d2dcb5b.tar.gz --output $HOME/.cache/nvim/tree-sitter-kitty.tar.gz

#info(install/latex): Downloading tree-sitter-latex...
curl --silent --fail --show-error --retry 7 -L https://github.com/latex-lsp/tree-sitter-latex/archive/7e0ecdc02926c7b9b2e0c76003d4fe7b0944f957.tar.gz --output $HOME/.cache/nvim/tree-sitter-latex.tar.gz

#info(install/lua): Downloading tree-sitter-lua...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-lua/archive/10fe0054734eec83049514ea2e718b2a56acd0c9.tar.gz --output $HOME/.cache/nvim/tree-sitter-lua.tar.gz

#info(install/luadoc): Downloading tree-sitter-luadoc...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-luadoc/archive/873612aadd3f684dd4e631bdf42ea8990c57634e.tar.gz --output $HOME/.cache/nvim/tree-sitter-luadoc.tar.gz

#info(install/luap): Downloading tree-sitter-luap...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-luap/archive/c134aaec6acf4fa95fe4aa0dc9aba3eacdbbe55a.tar.gz --output $HOME/.cache/nvim/tree-sitter-luap.tar.gz

#info(install/make): Downloading tree-sitter-make...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-make/archive/70613f3d812cbabbd7f38d104d60a409c4008b43.tar.gz --output $HOME/.cache/nvim/tree-sitter-make.tar.gz

#info(install/markdown): Downloading tree-sitter-markdown...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-markdown/archive/f969cd3ae3f9fbd4e43205431d0ae286014c05b5.tar.gz --output $HOME/.cache/nvim/tree-sitter-markdown.tar.gz

#info(install/markdown_inline): Downloading tree-sitter-markdown_inline...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-markdown/archive/f969cd3ae3f9fbd4e43205431d0ae286014c05b5.tar.gz --output $HOME/.cache/nvim/tree-sitter-markdown_inline.tar.gz

#info(install/python): Downloading tree-sitter-python...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-python/archive/v0.25.0.tar.gz --output $HOME/.cache/nvim/tree-sitter-python.tar.gz

#info(install/query): Downloading tree-sitter-query...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-query/archive/fc5409c6820dd5e02b0b0a309d3da2bfcde2db17.tar.gz --output $HOME/.cache/nvim/tree-sitter-query.tar.gz

#info(install/regex): Downloading tree-sitter-regex...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-regex/archive/b2ac15e27fce703d2f37a79ccd94a5c0cbe9720b.tar.gz --output $HOME/.cache/nvim/tree-sitter-regex.tar.gz

#info(install/sql): Downloading tree-sitter-sql...
curl --silent --fail --show-error --retry 7 -L https://github.com/derekstride/tree-sitter-sql/archive/851e9cb257ba7c66cc8c14214a31c44d2f1e954e.tar.gz --output $HOME/.cache/nvim/tree-sitter-sql.tar.gz

#info(install/terraform): Downloading tree-sitter-terraform...
curl --silent --fail --show-error --retry 7 -L https://github.com/MichaHoffmann/tree-sitter-hcl/archive/64ad62785d442eb4d45df3a1764962dafd5bc98b.tar.gz --output $HOME/.cache/nvim/tree-sitter-terraform.tar.gz

#info(install/toml): Downloading tree-sitter-toml...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-toml/archive/64b56832c2cffe41758f28e05c756a3a98d16f41.tar.gz --output $HOME/.cache/nvim/tree-sitter-toml.tar.gz

#info(install/vim): Downloading tree-sitter-vim...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-vim/archive/3092fcd99eb87bbd0fc434aa03650ba58bd5b43b.tar.gz --output $HOME/.cache/nvim.tar.gz

#info(install/vimdoc): Downloading tree-sitter-vimdoc...
curl --silent --fail --show-error --retry 7 -L https://github.com/neovim/tree-sitter-vimdoc/archive/f061895a0eff1d5b90e4fb60d21d87be3267031a.tar.gz --output $HOME/.cache/nvimdoc.tar.gz

#info(install/xml): Downloading tree-sitter-xml...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-xml/archive/5000ae8f22d11fbe93939b05c1e37cf21117162d.tar.gz --output $HOME/.cache/nvim/tree-sitter-xml.tar.gz

#info(install/yaml): Downloading tree-sitter-yaml...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-yaml/archive/4463985dfccc640f3d6991e3396a2047610cf5f8.tar.gz --output $HOME/.cache/nvim/tree-sitter-yaml.tar.gz

#info(install/hcl): Downloading tree-sitter-hcl...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-hcl/archive/64ad62785d442eb4d45df3a1764962dafd5bc98b.tar.gz --output $HOME/.cache/nvim/tree-sitter-hcl.tar.gz

#info(install/dtd): Downloading tree-sitter-dtd...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter-grammars/tree-sitter-xml/archive/5000ae8f22d11fbe93939b05c1e37cf21117162d.tar.gz --output $HOME/.cache/nvim/tree-sitter-dtd.tar.gz

#info(install/rust): Downloading tree-sitter-rust...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-rust/archive/77a3747266f4d621d0757825e6b11edcbf991ca5.tar.gz --output $HOME/.cache/nvim/tree-sitter-rust.tar.gz

# info(install/comment): Downloading tree-sitter-comment...
curl --silent --fail --show-error --retry 7 -L https://github.com/stsewd/tree-sitter-comment/archive/66272d2b6c73fb61157541b69dd0a7ce7b42a5ad.tar.gz --output $HOME/.cache/nvim/tree-sitter-comment.tar.gz

# info(install/html): Downloading tree-sitter-html...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-html/archive/73a3947324f6efddf9e17c0ea58d454843590cc0.tar.gz --output $HOME/.cache/nvim/tree-sitter-html.tar.gz

# info(install/css): Downloading tree-sitter-css...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-css/archive/dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f.tar.gz --output $HOME/.cache/nvim/tree-sitter-css.tar.gz

# info(install/go): Downloading tree-sitter-go...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-go/archive/2346a3ab1bb3857b48b29d779a1ef9799a248cd7.tar.gz --output $HOME/.cache/nvim/tree-sitter-go.tar.gz

# info(install/javascript): Downloading tree-sitter-javascript...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-javascript/archive/58404d8cf191d69f2674a8fd507bd5776f46cb11.tar.gz --output $HOME/.cache/nvim/tree-sitter-javascript.tar.gz

# info(install/tsx): Downloading tree-sitter-tsx...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-typescript/archive/75b3874edb2dc714fb1fd77a32013d0f8699989f.tar.gz --output $HOME/.cache/nvim/tree-sitter-tsx.tar.gz

# nfo(install/typescript): Downloading tree-sitter-typescript...
curl --silent --fail --show-error --retry 7 -L https://github.com/tree-sitter/tree-sitter-typescript/archive/75b3874edb2dc714fb1fd77a32013d0f8699989f.tar.gz --output $HOME/.cache/nvim/tree-sitter-typescript.tar.gz

