# imports
include theme.conf

# font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

# cursor
cursor_blink_interval 0
cursor_shape block

# mouse
mouse_hide_wait 10.0

# misc
hide_window_decorations yes

enable_audio_bell no

confirm_os_window_close 0

map ctrl+shift+r load_config_file

map ctrl+0 change_font_size all 0

# Enable layouts
enabled_layouts splits,stack,tall,fat,grid

# Tab bar style
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: "
active_tab_title_template "{index}: "

# open new tab
map ctrl+shift+t launch --type=tab --cwd=current --title="-" zsh

# rename a tab
map ctrl+shift+r set_tab_title

# select tabs
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

# Scrollback
scrollback_lines 10000

# Copy/paste
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# splits
map ctrl+shift+minus launch --location=hsplit --cwd=current zsh
map ctrl+shift+backslash launch --location=vsplit --cwd=current zsh

# macOC - . This will let you use the alt key to type unicode characters again instead of passing the alt key directly to the shell or whatever you're running.
# macos_option_as_alt no
