-- vim.pack.add({"https://github.com/igorlfs/nvim-dap-view"})
-- require("dap-view").setup({
--     winbar = {
--         sections = { "scopes", "breakpoints", "threads", "repl" },
--         default_section = "repl",
--     },
--     switchbuf = "uselast",
--     auto_toggle = true,
-- })
