require('plugins.mini-configs')
require('plugins.treesitter')
require('plugins.blink')
require('plugins.whichkey')
require('plugins.snacks')
require('plugins.noice')
require('plugins.pyrepl')
require('plugins.dap-view')
require('plugins.dap')
require('plugins.spellwarn')

require('plugins.code-companion')
require('plugins.copilot')
-- require('plugins.plugins-keymaps')
